{
    'name': "Customer Invoice Margin",
    'author': 'Ascetic Business Solution',
    'category': 'Account',
    'summary': """Margin Percentage in Customer Invoice""",
    'license': 'AGPL-3',
    'website': 'http://www.asceticbs.com',
    'description': """""",
    'version': '11.0.1.0.0',
    'depends': ['account','sale_margin'],
    'data': ['views/account_invoice_view.xml'],
    'images': ['static/description/banner.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
